apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mktplace-develop-api-gateway
build:
  local:
    push: false
  artifacts:
    - image: newerton/api-gateway
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/secrets.yaml
      - k8s/deployment.yaml
      - k8s/service.yaml
