# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s-namespace
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s-namespace
  name: api-gateway-k8s-secret
type: Opaque
stringData:
  DEBUG: "1"
  KEYCLOAK_BASE_URL: http://keycloak:8080
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_CLIENT_ID: api-gateway
  KEYCLOAK_SECRET: 13d176b5-d080-4a88-87e3-a7ccd0c47808
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgrFuOVj6xjrPee/KNuxCM/1Jgzrtv7GZgklObcgQAIhhioLLWWpOJXbK7VSalQY8AZr5x/QOrH5RgcVVyuRVQTurO7KiN7ZCcgjh47lP0Zs6fIJayyQVNhH9bDyqYhIPH6l9pDwUA/EmfK78MQE9MnUelk75sB2LdVlS3Q+1vLyjLlvSKXAkfdWwIvxZwaxS67UGemKh/PTFwinkGHXSKdEfOxqI2FgMl5VD6iNW6ZLOr88xHMNFi01bTs1KMXsQbJ4TRa9kGvByhh8puMRiea5ZwK2gjA7wAoHV/ip92BiyEvwhiWxLbudMhXe1xEFV0sEwEnYcedpyMj4iUkS2BQIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: e72956a8-271e-4272-83b7-00c9702b8042
