# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s-namespace
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s-namespace
  name: api-gateway-k8s-secret
type: Opaque
stringData:
  DEBUG: "1"
  KEYCLOAK_BASE_URL: http://keycloak:8080
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_CLIENT_ID: api-gateway
  KEYCLOAK_SECRET: 7c6020e5-e493-4d18-a5f4-76034d7ffe22
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg7fxeDJ5cDt5nBJcXDMoeyxB0IPsLxb1rpB9LQFMZqeY7wXiqK4cO1JHwmGP2OIiNJ9uFmSN8/0NkWvxCrYpMofvl3UwE+eER9s7CNnxQWYkJJ2nn2tOVcC4Y+MTP9wgkuoulmNiblM9Dqt266TRGB7ol6jYPx9OAGBZxYCUFXbdl+/NnwEoZuQx+k/EGxms65K1OO1sYaCUed35Cewlg32rABE5LWL9xudtyGWY1r/N/Cx6R0pV9bDKRMJU5pGu04tkdI2DgAPmgyg5kCBfaFiPsb8xVp2tABwyzOUbAjUejNP079D6zLqzaXnT8ok3r9LcK4codxkdeaFEYE6H0QIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: c4f370f2-6737-4255-b252-62c4f1167887
