apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  labels:
    app: api-gateway
type: Opaque
stringData:
  MODE: development
  API_PORT: "3000"
  API_LOG_ENABLE: "true"
  API_LIGHTSHIP_PORT: "4000"
  API_AUTH_ENGINE_PORT: "3001"
  API_USER_ENGINE_PORT: "3002"
  API_PRODUCT_ENGINE_PORT: "3003"
  DB_VENDOR: mysql
  DB_ADDR: mysql
  DB_DATABASE: mktplace_api_gateway
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
  DB_LOGGING: "true"
  DB_AUTH: ""
  KAFKA_BROKER_HOST: mktplace-kafka.mktplace-develop.svc.cluster.local
  KAFKA_BROKER_PORT: "9092"
  KEYCLOAK_DEBUG: "1"
  KEYCLOAK_BASE_EXTERNAL_URL: http://localhost:8080
  KEYCLOAK_BASE_INTERNAL_URL: http://localhost:8080
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_API_GATEWAY_CLIENT_ID: api-gateway
  KEYCLOAK_API_GATEWAY_SECRET: UiD4K0IZULfaEWcAxBaRtR3mnEhERGcR
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwsNbEAsekj1L0IbVf26uliAy22ger+2psI7i6uLuRt8yemaKOye+P4MOiaeHjl7RcBz9B/fICTnUa1ISsewtSLsE7BoPPMkqJBLDy416fzuZC6sVZvYRSw0MJyL2SqyK7TXk9oYXbvecPkCKYxRj+ecv5Y8/0aBpJ6hhlxXPELijUQc3G6kaGyoEK+uigIzU5z+y3WhxOQZqi+wYWIsykJaH3nUPpxo3uB7w1xikNqNMcyTUj6mmArdFkozzG6lCCPHMyjXPael0BfIDnl5mhv/G6PRa3i//5aW/KYmi/hqZJNZu/lCqSjgRdL8mqoyqpqmv87IBbTDY962bMw/yBQIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: JPu7xOzwC7r8qxKI9pfWtNtjZ8GU8glM
  RABBITMQ_PROTOCOL: amqps
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5671"
  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: admin
  RABBITMQ_CERTIFICATE_AUTH: ""
